#ifndef ApproxArgonProperties_hxx_seen
/// Capture some generic properties for argon.
#include <HEPUnits.hxx>

namespace approxArgon {
    /// The approximate activation energy for argon.
    const double Activation = 19.5*unit::eV;

    /// The approximate probability that a thermal electron generated by a MIP
    /// will recombine with it's source ion.
    const double Recombination = 0.43;

    /// The approximate energy per thermal electron.  This times the charge is
    /// the approximate energy.
    const double Energy = 34.0*unit::eV;

    /// The approximate number of thermal electroncs collected per unit energy.
    const double Electrons = 1.0/Energy;

    /// The approximate dE/dX for a MIP in argon.
    const double dEdX = 1.8*unit::MeV/unit::cm;

    /// The approximate dE/dX for a MIP in argon.
    const double dElectrondX = dEdX*Electrons;

};
#endif
